version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14268:14268"
      - "16686:16686"
  influxdb:
    image: influxdb:1.8.5
    environment:
      - "INFLUXDB_DB=krakend"
      - "INFLUXDB_USER=krakend-dev"
      - "INFLUXDB_USER_PASSWORD=pas5w0rd"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=supersecretpassword"
    ports:
      - "8086:8086"
  elasticsearch:
    image: elasticsearch:5.6.13-alpine
    environment:
      - "discovery.type=single-node"
    ports:
      - "19200:9200"
      - "9300:9300"
  kibana:
    image: kibana:5.6.13
    ports:
      - "5601:5601"
  logstash:
    image: logstash:5.6.13-alpine
    ports:
      - "12201:12201/udp"
      - "5044:5044"
    environment:
      - "xpack.monitoring.elasticsearch.url=http://elasticsearch:9200"
    volumes:
      - ./config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    command: ["-f", "/usr/share/logstash/pipeline/logstash.conf"]
  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    volumes:
      - "./config/grafana/datasources/all.yml:/etc/grafana/provisioning/datasources/all.yml"
      - "./config/grafana/dashboards/all.yml:/etc/grafana/provisioning/dashboards/all.yml"
      - "./config/grafana/krakend:/var/lib/grafana/dashboards/krakend"
  fake_api:
    image: jaxgeller/lwan
    volumes:
      - ./data:/lwan/wwwroot
    ports:
      - "8000:8080"
  krakend:
    image: 052351007912.dkr.ecr.us-east-1.amazonaws.com/krakend-ee:1.3.0
    volumes:
      - ./config/krakend:/etc/krakend
    command: ["run", "-c", "krakend.json", "--accept-eula", "-d"]
    environment:
      - FC_ENABLE=1
      - FC_SETTINGS=/etc/krakend/settings
      - FC_PARTIALS=/etc/krakend/partials
      - FC_TEMPLATES=/etc/krakend/templates
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    depends_on:
      - fake_api
      - jaeger
  jwt_revoke:
    build:
      context: ./jwt-revoker
    ports:
      - "9000:8080"
    depends_on:
      - krakend
