key: websocket
val: 
  input_headers:
    - Cookie
    - Authorization
  connect_event: true
  disconnect_event: true
  read_buffer_size: 4096
  write_buffer_size: 4096
  message_buffer_size: 4096
  max_message_size: 3200000
  write_wait: "10s"
  pong_wait: "60s"
  ping_period: "54s"
  max_retries: 0
  backoff_strategy: exponential
