github: "https://api.github.com"
influxdb: "localhost:8086"
logstash: "localhost:12201"
chat: "localhost:8888"
rabbitmq: "localhost:5672"
grpc_flights: "localhost:4242"
grpc_trains: "localhost:4243"
fake_api: "localhost:8000"